apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  labels:
    app: etok
  name: runs.etok.dev
spec:
  group: etok.dev
  names:
    kind: Run
    listKind: RunList
    plural: runs
    singular: run
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.command
      name: Command
      type: string
    - jsonPath: .spec.workspace
      name: Workspace
      type: string
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RunSpec defines the desired state of Run
            properties:
              args:
                items:
                  type: string
                type: array
              command:
                enum:
                - apply
                - destroy
                - force-unlock
                - get
                - import
                - init
                - output
                - plan
                - refresh
                - sh
                - state list
                - state mv
                - state pull
                - state push
                - state rm
                - state show
                - taint
                - untaint
                - validate
                type: string
              configMap:
                type: string
              configMapKey:
                type: string
              configMapPath:
                type: string
              handshake:
                description: Toggle whether runner should wait for a handshake from
                  client
                type: boolean
              handshakeTimeout:
                default: 10s
                description: How long to wait for handshake before timing out
                type: string
              verbosity:
                type: integer
              workspace:
                type: string
            required:
            - command
            - configMap
            - configMapKey
            - configMapPath
            - handshake
            - handshakeTimeout
            - workspace
            type: object
          status:
            description: RunStatus defines the observed state of Run
            properties:
              phase:
                type: string
            required:
            - phase
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
