apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  labels:
    app: etok
  name: runs.etok.dev
spec:
  group: etok.dev
  names:
    kind: Run
    listKind: RunList
    plural: runs
    singular: run
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.command
      name: Command
      type: string
    - jsonPath: .spec.workspace
      name: Workspace
      type: string
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RunSpec defines the desired state of Run
            properties:
              args:
                description: The arguments to be passed to the command
                items:
                  type: string
                type: array
              command:
                description: The command to run on the pod
                enum:
                - apply
                - destroy
                - plan
                - sh
                type: string
              configMap:
                description: ConfigMap containing the tarball to extract on the pod
                type: string
              configMapKey:
                description: The config map key identifying the tarball to extract
                type: string
              configMapPath:
                description: The path within the archive to the root module
                type: string
              handshake:
                description: Enable TTY on pod and await handshake string from client
                type: boolean
              handshakeTimeout:
                default: 10s
                description: How long to wait for handshake before timing out
                type: string
              verbosity:
                description: Logging verbosity.
                minimum: 0
                type: integer
              workspace:
                description: The workspace of the run.
                type: string
            required:
            - command
            - configMap
            - configMapKey
            - configMapPath
            - workspace
            type: object
          status:
            description: RunStatus defines the observed state of Run
            properties:
              phase:
                description: Current phase of the run's lifecycle.
                type: string
              reconciled:
                description: True if resource has been reconciled at least once.
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
