apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  labels:
    app: stok
  name: workspaces.stok.goalspike.com
spec:
  group: stok.goalspike.com
  names:
    kind: Workspace
    listKind: WorkspaceList
    plural: workspaces
    singular: workspace
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.queue
      name: Queue
      type: string
    - jsonPath: .spec.backend.type
      name: Backend
      type: string
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Workspace is the Schema for the workspaces API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: WorkspaceSpec defines the desired state of Workspace
            properties:
              backend:
                properties:
                  config:
                    additionalProperties:
                      type: string
                    type: object
                  type:
                    enum:
                    - local
                    - remote
                    - artifactory
                    - azurerm
                    - consul
                    - cos
                    - etcd
                    - etcdv3
                    - gcs
                    - http
                    - manta
                    - oss
                    - pg
                    - s3
                    - swift
                    type: string
                type: object
              cache:
                description: WorkspaceSpec defines the desired state of Workspace's
                  cache storage
                properties:
                  size:
                    type: string
                  storageClass:
                    type: string
                type: object
              debug:
                type: boolean
              handshake:
                description: Toggle whether runner should wait for a handshake from
                  client
                type: boolean
              handshakeTimeout:
                default: 10s
                description: How long to wait for handshake before timing out
                type: string
              privilegedCommands:
                items:
                  type: string
                type: array
              secretName:
                default: stok
                type: string
              serviceAccountName:
                default: stok
                type: string
            required:
            - backend
            - handshake
            - handshakeTimeout
            - privilegedCommands
            type: object
          status:
            description: WorkspaceStatus defines the observed state of Workspace
            properties:
              phase:
                type: string
              queue:
                items:
                  type: string
                type: array
            required:
            - phase
            - queue
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
